name: hasanati
description: "تطبيق حسناتي الإسلامي - القرآن الكريم والأذكار"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true